apiVersion: cnab.technosophos.com/v1
kind: Release
metadata:
  # This will be used as the name of the install
  name: cowsay
spec:
  # the bundle to be pulled from an OCI repository
  bundle: technosophos/porter-cowsay:latest
  # the VALUES to be supplied to parameters defined on the bundle
  parameters:
    - name: install_message
      value: Moooo
    - name: uninstall_message
      value: Baaaah
  credentials:
    - name: bogo_token
      value: bogo_value
